# fly.toml app configuration file generated for spring-firefly-8743 on 2023-10-17T21:35:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cineclub-frontend-angular"
primary_region = "eze"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]